####################
#      Leaper      #
#    by sgtcaze    #
####################

# Slightly faster than normal walk speed, it helps the transition from leaping.
SmootherWalk: true

# How high and far the players travel. This matches The ShotBow Network!
multiply: 1.6
height: 1

Particles:
  Smoke: false
  MobSpawnerFlames: false
  EnderSignal: false
  PotionBreak: false

Sounds:
  BatTakeOff: false
  EnderDragonWings: false
  ShootArrow: false

Worlds:
  EnabledWorlds:
  - world
  DisabledWorlds:
  - example